### ISSUE TITLE
Move to TextKit 2

### ISSUE THREAD

**Issue by mchakravarty** [mchakravarty/CodeEditorView#79]
* [x] Configure `NSTextView` in TextKit 2 mode
* [x] Configure `UITextView` in TextKit 2 mode
* [x] Line numbers
* [x] ~Avoid that the insertion point moves underneath the gutter on empty lines~ — moved to #84
* [x] Message views
  * [x] No transparency in the line version
  * [x] Can we still cache the line fragment rect for each message or is there a better option?
  * [x] Colour highlight in gutter
* [x] Minimap
  * [x] Configuration of the minimap
  * [x] Type setting of the minimap
* [x] Simplify tiling on the basis of the new minimap sizing
* [x] Minimap for iOS — mostly done, but still needs #83 
* [x] ~Processing of typed text is too slow when the text gets longer (probably waiting for layout...)~ — moved to #85
* [x] ~Fix gutter redraw on scrolling in iOS~ — now covered by #87 
* [x] Search for "TextKit 2" FIXMEs
